feat: part 1
sgroup-99/libft pull request #1
Opened 2021-05-20 23:14 UTC by bh90210

2021-05-23 01:19 UTC, bh90210 reviewed
# needs fixing
- [x] atoi
- [x] strncmp
- [x] strrchr
- [x] strchr
- [x] strrchr
- [x] strlcat

2021-05-25 03:14 UTC, bh90210 reviewed
most should be `OK`, there is one problem with `memmove` but I am on it :+1:

2021-05-25 03:26 UTC, bh90210 reviewed
all done, all tests passing, please put some human input :)

2021-05-25 04:32 UTC, bh90210 commented on ft_memmove.c
> +}
https://stackoverflow.com/questions/13339582/why-is-linux-memmove-implemented-the-way-it-is

2021-05-25 09:08 UTC, ignan1 requested changes
ft_strnstr is failing when s2 is only 1 character long

2021-05-25 13:02 UTC, bh90210 reviewed
fixed :+1:

2021-05-25 13:06 UTC, merged